#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Always mesh this case (do not depend on sibling VoF tutorial)
./Allmesh

# Copy the fields into the processor directories
runApplication -a decomposePar -fields -copyZero

# Run
runParallel $(getApplication)

# Reconstruct
runApplication reconstructPar

#------------------------------------------------------------------------------
